### ISSUE TITLE
0.3w Errata

### ISSUE THREAD

**Issue by joshajohnson** [joshajohnson/entropy#1]
### Bugs 

- [X] Row3 should be moved to P0.08 (Pin 44) to keep all inputs on same port for power consumption.
- [X] One of the rotary encoders needs to be moved off port 0 due to limit of 8 interrupts per port. (move ENC_4)
- [X] 3V3 needs to be added to programming header for JLink to detect voltage

### Improvements

- [X] Add more RGB (WS2812C), place before SK6812-Mini-E in chain.
- [X] Check PFET has enough current carrying capacity for the LEDs (current one can do 4A)
- [X] Change level shifter to SN74LVC1T45DBV for lower quiescent current draw
- [X] Swap above part to SC70 due to component shortages
- [X] Add jumpers for Standby and Charge LEDs.
- [X] Change charge resistor values to 5k1, maybe decrease blue LED to 1k.
- [X] Swap 10K resistors for 5k1
- [X] Diode OR VBAT and VUSB into 3v3 regulator
- [X] ~Flip bottom stabs for a smaller PCB size / larger bezel.~
- [X] Breakout all unused pins
- [X] Extend USB connector by ~5mm (currently 6mm from flush)
- [X] Change case design per above

### TODO

- [x] Update bootloader to flash user LED ~(and maybe change direction of LED to active low?).~
- [X] Swap Green and Blue LEDs (so user is blue, standby is green).
- [X] Test fit acrylic case
- [X] Layout 0.4 PCB and order
